name: "Security Scan"

on: [push]

jobs:

  # job 1 DEPENDECY CHECK
  dependecy-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Snyk Open Source
        uses: snyk/actions/node@master
        env: 
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --all-projects --severity-threshold=low

  # job 2 STATIC CODE ANALYSIS
  code-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - name: Snyk Code
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --severity-threshold=low

  image_scan:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t vulnerable-app:local .

      - name: Snyk container scan  
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: vulnerable-app:local
          args: --file=Dockerfile --severity-threshold-high