name: "Security Scan"

on: [push]
   
permissions: 
  security-events: write

jobs:

  # job 1 DEPENDECY CHECK
  dependecy-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Snyk Open Source
        uses: snyk/actions/node@master
        continue-on-error: true
        env: 
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --all-projects --sarif-file-output=snyk-deps.sarif --severity-threshold=low

      - name: Upload sarif to github
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: snyk-deps.sarif

  # job 2 STATIC CODE ANALYSIS
  code-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - name: Snyk Code
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --severity-threshold=low --sarif-file-output=snyk-code.sarif

      - name: Upload sarif to github
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: snyk-code.sarif

  image_scan:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t vulnerable-app:local .

      - name: Snyk container scan  
        uses: snyk/actions/docker@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: vulnerable-app:local
          args: --file=Dockerfile --severity-threshold=high
          sarif: true

      - name: Upload sarif to github
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: snyk.sarif

  iac_scan:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Run iac scan
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: iac test
          args: terraform/main.tf --sarif-file-output=snyk-iac.sarif

      - name: Upload sarif to github
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: snyk-iac.sarif

  # gatekeeper keeps track of the results of the other jobs
  gatekeeper:
    runs-on: ubuntu-latest
    if: always()
    needs: [dependecy-scan, code-scan, image_scan, iac_scan] # wait for all these jobs
    steps:
      - name: Evaluate security results
        run: |
          if [[ "${{ needs.dependecy-scan.result }}" != "success" || \
                "${{ needs.code-scan.result }}" != "success" || \
                "${{ needs.image_scan.result }}" != "success" || \
                "${{ needs.iac-scan.result }}" != "success" ]]; then
            echo "Security scans found vulnerabilities. Blocking merge."
            exit 1 # This physically fails the job and blocks the PR
          fi
          echo "All security scans passed!"
