name: "Security Scan"

on: [push]
   
permissions: 
  security-events: write

jobs:
  # job 1 DEPENDECY CHECK
  dependecy_scan:
    runs-on: ubuntu-latest
    outputs: 
      outcome: ${{ steps.snyk-test.outcome }}
    steps:
      - uses: actions/checkout@v4
      - name: Snyk Open Source
        id: snyk-test
        uses: snyk/actions/node@master
        continue-on-error: true
        env: 
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --all-projects --sarif-file-output=snyk-deps.sarif --severity-threshold=low

      - name: Upload sarif to github
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: snyk-deps.sarif

  # job 2 STATIC CODE ANALYSIS
  code_scan:
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{ steps.snyk-test.outcome }}
    steps:
      - uses: actions/checkout@v4 
      - name: Snyk Code
        id: snyk-test
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --severity-threshold=low --sarif-file-output=snyk-code.sarif

      - name: Upload sarif to github
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: snyk-code.sarif

  image_scan:
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{ steps.snyk-test.outcome }}
    steps: 
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t vulnerable-app:local .

      - name: Snyk container scan  
        id: snyk-test
        uses: snyk/actions/docker@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: vulnerable-app:local
          args: --file=Dockerfile --severity-threshold=high
          sarif: true

      - name: Upload sarif to github
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: snyk.sarif

  iac_scan:
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{ steps.snyk-test.outcome }}
    steps: 
      - uses: actions/checkout@v4
      - name: Run iac scan
        id: snyk-test
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: iac test
          args: terraform/main.tf --sarif-file-output=snyk-iac.sarif

      - name: Upload sarif to github
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: snyk-iac.sarif

  # gatekeeper keeps track of the results of the other jobs
  gatekeeper:
    runs-on: ubuntu-latest
    if: always()
    needs: [dependecy_scan, code_scan, image_scan, iac_scan]
    steps:
      - name: Evaluate security results
        run: |
          # We check if any of the outcomes were 'failure'
          if [[ "${{ needs.dependecy_scan.outputs.outcome }}" == "failure" || \
                "${{ needs.code_scan.outputs.outcome }}" == "failure" || \
                "${{ needs.image_scan.outputs.outcome }}" == "failure" || \
                "${{ needs.iac_scan.outputs.outcome }}" == "failure" ]]; then
            echo "Security scans found vulnerabilities. Blocking merge."
            exit 1
          fi
          echo "All security scans passed!"
