name: "Security Scan"

on: [push]

jobs:

  dependecy-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Snyk Open Source
        uses: snyk/actions/node@master
        with:
          command: test
          args: --all-projects --severity-threshold=low

  code-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Snyk Code
      - uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --severity-threshold=low


